package com.esports.Client.GUI;

import com.esports.Server.rmiserver.ServiceInterface;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * This GUI will display the selected chart 
 * Design related codes are taken from YouTube 
 * URL : https://www.youtube.com/watch?v=ddaY9461FJQ
 * @author Lasindu Ruwin
 */
public class StatusUI extends javax.swing.JFrame {
    //variables for XY coordinations of the window
    int x;
    int y;
    /**
     * Creates new form StatusUI
     */
    public StatusUI() {
        initComponents();
    }
    
    /**
     * Methods for switching color on click
     * @param lbl label that needs color change 
     */
    public void setlblcolor(JLabel lbl)
    {
        lbl.setBackground(new Color(0,153,255));
    }
    public void resetlblcolor(JLabel lbl)
    {
        lbl.setBackground(new Color(0,0,0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selection = new javax.swing.JPanel();
        Display1btn = new javax.swing.JLabel();
        Display2btn = new javax.swing.JLabel();
        Display3btn = new javax.swing.JLabel();
        menubtn = new javax.swing.JLabel();
        exitbtn = new javax.swing.JLabel();
        DisplayName = new javax.swing.JPanel();
        display1 = new javax.swing.JPanel();
        chart1 = new javax.swing.JLabel();
        display2 = new javax.swing.JPanel();
        chart2 = new javax.swing.JLabel();
        display3 = new javax.swing.JPanel();
        chart3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("E-Sports Survey 2021");
        jLabel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        selection.setBackground(new java.awt.Color(0, 0, 0));
        selection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Display1btn.setBackground(new java.awt.Color(0, 0, 0));
        Display1btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Display1btn.setForeground(new java.awt.Color(255, 255, 255));
        Display1btn.setText("Popularity of the Games");
        Display1btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Display1btn.setOpaque(true);
        Display1btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Display1btnMouseClicked(evt);
            }
        });

        Display2btn.setBackground(new java.awt.Color(0, 0, 0));
        Display2btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Display2btn.setForeground(new java.awt.Color(255, 255, 255));
        Display2btn.setText("Streamers");
        Display2btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Display2btn.setOpaque(true);
        Display2btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Display2btnMouseClicked(evt);
            }
        });

        Display3btn.setBackground(new java.awt.Color(0, 0, 0));
        Display3btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Display3btn.setForeground(new java.awt.Color(255, 255, 255));
        Display3btn.setText("Playtime Analysis");
        Display3btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Display3btn.setOpaque(true);
        Display3btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Display3btnMouseClicked(evt);
            }
        });

        menubtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menubtn.setForeground(new java.awt.Color(255, 255, 255));
        menubtn.setText("Main Menu");
        menubtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        menubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubtnMouseClicked(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("Exit");
        exitbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout selectionLayout = new javax.swing.GroupLayout(selection);
        selection.setLayout(selectionLayout);
        selectionLayout.setHorizontalGroup(
            selectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Display1btn, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
            .addComponent(Display3btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Display2btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        selectionLayout.setVerticalGroup(
            selectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Display1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Display2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Display3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        DisplayName.setBackground(new java.awt.Color(0, 0, 0));
        DisplayName.setLayout(new java.awt.CardLayout());

        display1.setBackground(new java.awt.Color(0, 0, 0));

        chart1.setForeground(new java.awt.Color(255, 255, 255));
        chart1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chart1.setText("Please select an analysis category to display resulsts");
        chart1.setToolTipText("");

        javax.swing.GroupLayout display1Layout = new javax.swing.GroupLayout(display1);
        display1.setLayout(display1Layout);
        display1Layout.setHorizontalGroup(
            display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        display1Layout.setVerticalGroup(
            display1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DisplayName.add(display1, "card2");

        display2.setBackground(new java.awt.Color(0, 0, 0));

        chart2.setForeground(new java.awt.Color(255, 255, 255));
        chart2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chart2.setText("rsfsdfsdf");
        chart2.setToolTipText("");

        javax.swing.GroupLayout display2Layout = new javax.swing.GroupLayout(display2);
        display2.setLayout(display2Layout);
        display2Layout.setHorizontalGroup(
            display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        display2Layout.setVerticalGroup(
            display2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, display2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DisplayName.add(display2, "card2");

        display3.setBackground(new java.awt.Color(0, 0, 0));

        chart3.setForeground(new java.awt.Color(255, 255, 255));
        chart3.setText("Analysis display section 3");
        chart3.setToolTipText("");

        javax.swing.GroupLayout display3Layout = new javax.swing.GroupLayout(display3);
        display3.setLayout(display3Layout);
        display3Layout.setHorizontalGroup(
            display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, display3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        display3Layout.setVerticalGroup(
            display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DisplayName.add(display3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DisplayName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DisplayName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // Close btn
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked
   
    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // Position the window according to mouse dragging
        int codX = evt.getXOnScreen();
        int codY = evt.getYOnScreen();

        this.setLocation(codX-x, codY-y);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
       // Get the current position of the window .
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void Display1btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Display1btnMouseClicked
        // Analysis button 1
        setlblcolor(Display1btn);
        resetlblcolor(Display2btn);
        resetlblcolor(Display3btn);
        
        
        display1.setVisible(true);
        display2.setVisible(false);
        display3.setVisible(false);

        
        try {
             ServiceInterface rmi =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");           
            
            //get generated chart URL and convert it into and imageicon. Then setiing it to a label 
                        Image image = null;
			URL url = new URL(rmi.printGameChart());
			image = ImageIO.read(url).getScaledInstance(chart1.getWidth(), chart1.getHeight(), image.SCALE_SMOOTH);	
                        ImageIcon icon = new ImageIcon(image); 			
			chart1.setIcon(icon);
                        

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            Logger.getLogger(StatusUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Display1btnMouseClicked

    private void Display3btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Display3btnMouseClicked
        // Analysis button 3
        setlblcolor(Display3btn);
        resetlblcolor(Display1btn);
        resetlblcolor(Display2btn);
        
        
        display1.setVisible(false);
        display3.setVisible(true);
        display2.setVisible(false);
        
        
        try {
            
            ServiceInterface rmi =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");           
            
                        //get generated chart URL and convert it into and imageicon. Then setiing it to a label  
                        Image image = null;
			URL url = new URL(rmi.printTimeChart());
			image = ImageIO.read(url).getScaledInstance(chart3.getWidth(), chart3.getHeight(), image.SCALE_SMOOTH);	
                        ImageIcon icon = new ImageIcon(image); 			
			chart3.setIcon(icon);
                        

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            Logger.getLogger(StatusUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_Display3btnMouseClicked

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        //Exit Button
        System.exit(0);
    }//GEN-LAST:event_exitbtnMouseClicked

    private void menubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseClicked
        // Return to main menu button
        MainUI nxt = new MainUI();
        setVisible(false);
        nxt.setVisible(true);
    }//GEN-LAST:event_menubtnMouseClicked

    private void Display2btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Display2btnMouseClicked
        // Analysis button 2
        setlblcolor(Display2btn);
        resetlblcolor(Display1btn);
        resetlblcolor(Display3btn);
        
        
        display1.setVisible(false);
        display2.setVisible(true);
        display3.setVisible(false);
        
        
        try {
            
            ServiceInterface rmi =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");           
            
            //get generated chart URL and convert it into and imageicon. Then setiing it to a label 
                        Image image = null;
			URL url = new URL(rmi.printStreamerChart());
			image = ImageIO.read(url).getScaledInstance(chart2.getWidth(), chart2.getHeight(), image.SCALE_SMOOTH);	
                        ImageIcon icon = new ImageIcon(image); 			
			chart2.setIcon(icon);
                        

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            Logger.getLogger(StatusUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Display2btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatusUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Display1btn;
    private javax.swing.JLabel Display2btn;
    private javax.swing.JLabel Display3btn;
    private javax.swing.JPanel DisplayName;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel chart1;
    private javax.swing.JLabel chart2;
    private javax.swing.JLabel chart3;
    private javax.swing.JPanel display1;
    private javax.swing.JPanel display2;
    private javax.swing.JPanel display3;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel menubtn;
    private javax.swing.JPanel selection;
    // End of variables declaration//GEN-END:variables
}
