package com.esports.Client.GUI;

import com.esports.Server.rmiserver.ServiceInterface;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 * This is where the user will be able to answer the questions.
 * Each answer will be recorded in an array and sent to a database via RMI server
 * Design related codes are taken from YouTube 
 * URL : https://www.youtube.com/watch?v=ddaY9461FJQ
 * @author Lasindu Ruwin
 */
public class SurveyUI extends javax.swing.JFrame {
    //variables for XY coordinations of the window
    int x;
    int y;
    /**
     * Creates new form SurveyUI
     */
    public SurveyUI() {
        initComponents();
    }
    
    String[] answers = new String[7];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1 = new javax.swing.ButtonGroup();
        Q2 = new javax.swing.ButtonGroup();
        Q3 = new javax.swing.ButtonGroup();
        Q4 = new javax.swing.ButtonGroup();
        Q5 = new javax.swing.ButtonGroup();
        Q6 = new javax.swing.ButtonGroup();
        Q7 = new javax.swing.ButtonGroup();
        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Base = new javax.swing.JPanel();
        page1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Q1a1 = new javax.swing.JLabel();
        Q1a2 = new javax.swing.JLabel();
        Q1next = new javax.swing.JLabel();
        Q1b = new javax.swing.JRadioButton();
        Q1a = new javax.swing.JRadioButton();
        page2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Q2a1 = new javax.swing.JLabel();
        Q2a2 = new javax.swing.JLabel();
        Q2next = new javax.swing.JLabel();
        Q2a = new javax.swing.JRadioButton();
        Q2b = new javax.swing.JRadioButton();
        page3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Q2a3 = new javax.swing.JLabel();
        Q2a4 = new javax.swing.JLabel();
        Q3next = new javax.swing.JLabel();
        Q3a = new javax.swing.JRadioButton();
        Q3b = new javax.swing.JRadioButton();
        page4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Q2a5 = new javax.swing.JLabel();
        Q2a6 = new javax.swing.JLabel();
        Q4next = new javax.swing.JLabel();
        Q2a13 = new javax.swing.JLabel();
        Q2a14 = new javax.swing.JLabel();
        Q2a15 = new javax.swing.JLabel();
        Q2a16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Q4a = new javax.swing.JRadioButton();
        Q4b = new javax.swing.JRadioButton();
        Q4c = new javax.swing.JRadioButton();
        Q4d = new javax.swing.JRadioButton();
        Q4e = new javax.swing.JRadioButton();
        Q4f = new javax.swing.JRadioButton();
        page5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Q2a7 = new javax.swing.JLabel();
        Q2a8 = new javax.swing.JLabel();
        Q5next = new javax.swing.JLabel();
        Q2a17 = new javax.swing.JLabel();
        Q5a = new javax.swing.JRadioButton();
        Q5b = new javax.swing.JRadioButton();
        Q5c = new javax.swing.JRadioButton();
        page6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Q2a9 = new javax.swing.JLabel();
        Q2a10 = new javax.swing.JLabel();
        Q6next = new javax.swing.JLabel();
        Q6a = new javax.swing.JRadioButton();
        Q6b = new javax.swing.JRadioButton();
        page7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Q2a11 = new javax.swing.JLabel();
        Q2a12 = new javax.swing.JLabel();
        Submit = new javax.swing.JLabel();
        Q2a18 = new javax.swing.JLabel();
        Q7a = new javax.swing.JRadioButton();
        Q7b = new javax.swing.JRadioButton();
        Q7c = new javax.swing.JRadioButton();
        endpoint = new javax.swing.JPanel();
        exitbtn = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        menubtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("E-Sports Survey 2021");
        jLabel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Base.setLayout(new java.awt.CardLayout());

        page1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1. Do you play competitive Video Games ?");

        Q1a1.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q1a1.setForeground(new java.awt.Color(255, 255, 255));
        Q1a1.setText("No");

        Q1a2.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q1a2.setForeground(new java.awt.Color(255, 255, 255));
        Q1a2.setText("Yes");

        Q1next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q1next.setForeground(new java.awt.Color(255, 255, 255));
        Q1next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1next.setText("NEXT");
        Q1next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q1next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q1nextMouseClicked(evt);
            }
        });

        Q1b.setBackground(new java.awt.Color(0, 0, 0));
        Q1.add(Q1b);

        Q1a.setBackground(new java.awt.Color(0, 0, 0));
        Q1.add(Q1a);

        javax.swing.GroupLayout page1Layout = new javax.swing.GroupLayout(page1);
        page1.setLayout(page1Layout);
        page1Layout.setHorizontalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1Layout.createSequentialGroup()
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Q1next, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(page1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(page1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Q1a)
                                .addGap(0, 0, 0)
                                .addComponent(Q1a2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(page1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Q1b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q1a1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        page1Layout.setVerticalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Q1a2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Q1a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q1a1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q1b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Q1next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        Base.add(page1, "card2");

        page2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2. Do you prefer competitive gaming over casual (Single player) gaming?");

        Q2a1.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a1.setForeground(new java.awt.Color(255, 255, 255));
        Q2a1.setText("Yes");

        Q2a2.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a2.setForeground(new java.awt.Color(255, 255, 255));
        Q2a2.setText("No");

        Q2next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2next.setForeground(new java.awt.Color(255, 255, 255));
        Q2next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q2next.setText("NEXT");
        Q2next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q2next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q2nextMouseClicked(evt);
            }
        });

        Q2a.setBackground(new java.awt.Color(0, 0, 0));
        Q2.add(Q2a);

        Q2b.setBackground(new java.awt.Color(0, 0, 0));
        Q2.add(Q2b);

        javax.swing.GroupLayout page2Layout = new javax.swing.GroupLayout(page2);
        page2.setLayout(page2Layout);
        page2Layout.setHorizontalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2Layout.createSequentialGroup()
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Q2next, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(page2Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(page2Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Q2a)
                                .addComponent(Q2b))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Q2a2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Q2a1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        page2Layout.setVerticalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(page2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Q2a1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Q2a, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2a2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q2b, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Q2next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        Base.add(page2, "card3");

        page3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3. Are you a streamer?");

        Q2a3.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a3.setForeground(new java.awt.Color(255, 255, 255));
        Q2a3.setText("Yes");

        Q2a4.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a4.setForeground(new java.awt.Color(255, 255, 255));
        Q2a4.setText("No");

        Q3next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q3next.setForeground(new java.awt.Color(255, 255, 255));
        Q3next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q3next.setText("NEXT");
        Q3next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q3next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q3nextMouseClicked(evt);
            }
        });

        Q3a.setBackground(new java.awt.Color(0, 0, 0));
        Q3.add(Q3a);

        Q3b.setBackground(new java.awt.Color(0, 0, 0));
        Q3.add(Q3b);

        javax.swing.GroupLayout page3Layout = new javax.swing.GroupLayout(page3);
        page3.setLayout(page3Layout);
        page3Layout.setHorizontalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Q3next, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(page3Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(page3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(page3Layout.createSequentialGroup()
                                    .addComponent(Q3b)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Q2a4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(page3Layout.createSequentialGroup()
                                    .addComponent(Q3a)
                                    .addGap(0, 0, 0)
                                    .addComponent(Q2a3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        page3Layout.setVerticalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Q2a3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Q3a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q3b, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q2a4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(Q3next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );

        Base.add(page3, "card3");

        page4.setBackground(new java.awt.Color(0, 0, 0));
        page4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4. What would be your favorite competitive game?");
        page4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 11, 687, 31));

        Q2a5.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a5.setForeground(new java.awt.Color(255, 255, 255));
        Q2a5.setText("Valorant");
        page4.add(Q2a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 159, 31));

        Q2a6.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a6.setForeground(new java.awt.Color(255, 255, 255));
        Q2a6.setText("CS GO");
        page4.add(Q2a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 159, 35));

        Q4next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q4next.setForeground(new java.awt.Color(255, 255, 255));
        Q4next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q4next.setText("NEXT");
        Q4next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q4next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q4nextMouseClicked(evt);
            }
        });
        page4.add(Q4next, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 159, 31));

        Q2a13.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a13.setForeground(new java.awt.Color(255, 255, 255));
        Q2a13.setText("Mortal Kombat X");
        page4.add(Q2a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 159, 35));

        Q2a14.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a14.setForeground(new java.awt.Color(255, 255, 255));
        Q2a14.setText("Call of Duty 4");
        page4.add(Q2a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 159, 35));

        Q2a15.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a15.setForeground(new java.awt.Color(255, 255, 255));
        Q2a15.setText("Rainbow Six Siege");
        page4.add(Q2a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 159, 35));

        Q2a16.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a16.setForeground(new java.awt.Color(255, 255, 255));
        Q2a16.setText("Dota 2");
        page4.add(Q2a16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 159, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dota2.png"))); // NOI18N
        page4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 160, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/valorant.png"))); // NOI18N
        page4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 160, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/csgo.png"))); // NOI18N
        page4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 160, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cod4.png"))); // NOI18N
        page4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rainbow six.png"))); // NOI18N
        page4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 160, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mk.png"))); // NOI18N
        page4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 270, 50));

        Q4a.setBackground(new java.awt.Color(0, 0, 0));
        Q4.add(Q4a);
        page4.add(Q4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 81, -1, 30));

        Q4b.setBackground(new java.awt.Color(0, 0, 0));
        Q4.add(Q4b);
        page4.add(Q4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        Q4c.setBackground(new java.awt.Color(0, 0, 0));
        Q4.add(Q4c);
        page4.add(Q4c, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        Q4d.setBackground(new java.awt.Color(0, 0, 0));
        Q4.add(Q4d);
        page4.add(Q4d, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        Q4e.setBackground(new java.awt.Color(0, 0, 0));
        Q4.add(Q4e);
        page4.add(Q4e, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 30));

        Q4f.setBackground(new java.awt.Color(0, 0, 0));
        Q4.add(Q4f);
        page4.add(Q4f, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 30));

        Base.add(page4, "card3");

        page5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("5.How many hours do you play for a day?");

        Q2a7.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a7.setForeground(new java.awt.Color(255, 255, 255));
        Q2a7.setText("Less than 2 hours");

        Q2a8.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a8.setForeground(new java.awt.Color(255, 255, 255));
        Q2a8.setText("More than 5 hours");

        Q5next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q5next.setForeground(new java.awt.Color(255, 255, 255));
        Q5next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q5next.setText("NEXT");
        Q5next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q5next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q5nextMouseClicked(evt);
            }
        });

        Q2a17.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a17.setForeground(new java.awt.Color(255, 255, 255));
        Q2a17.setText("3-5 hours");

        Q5a.setBackground(new java.awt.Color(0, 0, 0));
        Q5.add(Q5a);

        Q5b.setBackground(new java.awt.Color(0, 0, 0));
        Q5.add(Q5b);

        Q5c.setBackground(new java.awt.Color(0, 0, 0));
        Q5.add(Q5c);

        javax.swing.GroupLayout page5Layout = new javax.swing.GroupLayout(page5);
        page5.setLayout(page5Layout);
        page5Layout.setHorizontalGroup(
            page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page5Layout.createSequentialGroup()
                .addGroup(page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Q5next, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(page5Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(page5Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Q5a)
                                .addComponent(Q5b)
                                .addComponent(Q5c))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Q2a8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Q2a7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Q2a17, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        page5Layout.setVerticalGroup(
            page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2a7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5a, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2a17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(page5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2a8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5c, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(Q5next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );

        Base.add(page5, "card3");

        page6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("6.Do you use third party training tools (ex: Aim lab) to improve your skills?");

        Q2a9.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a9.setForeground(new java.awt.Color(255, 255, 255));
        Q2a9.setText("Yes");

        Q2a10.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a10.setForeground(new java.awt.Color(255, 255, 255));
        Q2a10.setText("No");

        Q6next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q6next.setForeground(new java.awt.Color(255, 255, 255));
        Q6next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q6next.setText("NEXT");
        Q6next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q6next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q6nextMouseClicked(evt);
            }
        });

        Q6a.setBackground(new java.awt.Color(0, 0, 0));
        Q6.add(Q6a);

        Q6b.setBackground(new java.awt.Color(0, 0, 0));
        Q6.add(Q6b);

        javax.swing.GroupLayout page6Layout = new javax.swing.GroupLayout(page6);
        page6.setLayout(page6Layout);
        page6Layout.setHorizontalGroup(
            page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page6Layout.createSequentialGroup()
                .addGroup(page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Q6next, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(page6Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(page6Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Q6b)
                                .addComponent(Q6a))
                            .addGroup(page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Q2a10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Q2a9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        page6Layout.setVerticalGroup(
            page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(page6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Q2a9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(Q6a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(Q2a10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(page6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Q6b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(Q6next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        Base.add(page6, "card3");

        page7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("7.What do you think about your rank/level progression compared friends?");

        Q2a11.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a11.setForeground(new java.awt.Color(255, 255, 255));
        Q2a11.setText("Slow");

        Q2a12.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a12.setForeground(new java.awt.Color(255, 255, 255));
        Q2a12.setText("Average");

        Submit.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit.setText("Submit");
        Submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });

        Q2a18.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a18.setForeground(new java.awt.Color(255, 255, 255));
        Q2a18.setText("Fast");

        Q7a.setBackground(new java.awt.Color(0, 0, 0));
        Q7.add(Q7a);

        Q7b.setBackground(new java.awt.Color(0, 0, 0));
        Q7.add(Q7b);

        Q7c.setBackground(new java.awt.Color(0, 0, 0));
        Q7.add(Q7c);

        javax.swing.GroupLayout page7Layout = new javax.swing.GroupLayout(page7);
        page7.setLayout(page7Layout);
        page7Layout.setHorizontalGroup(
            page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page7Layout.createSequentialGroup()
                .addGroup(page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(page7Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(page7Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Q7a)
                                .addComponent(Q7b)
                                .addComponent(Q7c))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Q2a12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Q2a11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Q2a18, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        page7Layout.setVerticalGroup(
            page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2a11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q7a, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2a12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q7b, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(page7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q2a18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q7c, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        Base.add(page7, "card3");

        endpoint.setBackground(new java.awt.Color(0, 0, 0));

        exitbtn.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbtn.setText("Exit");
        exitbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Thank You for Participating in our Survey");

        menubtn.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        menubtn.setForeground(new java.awt.Color(255, 255, 255));
        menubtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menubtn.setText("Menu");
        menubtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        menubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout endpointLayout = new javax.swing.GroupLayout(endpoint);
        endpoint.setLayout(endpointLayout);
        endpointLayout.setHorizontalGroup(
            endpointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endpointLayout.createSequentialGroup()
                .addGroup(endpointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endpointLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(endpointLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(endpointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        endpointLayout.setVerticalGroup(
            endpointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, endpointLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        Base.add(endpoint, "card3");

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // Close btn
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        /**
         * Allows Positioning of the window according to mouse dragging
         */
        int codX = evt.getXOnScreen();
        int codY = evt.getYOnScreen();

        this.setLocation(codX-x, codY-y);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        /**
         * Get the current position of the window .
         */
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void Q1nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1nextMouseClicked
        /**
         * Sends the radio button and button group to the RMI server's function and inserts the return value to a String array 
         */       
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[0]=rmiserv.YNAnswer(Q1a, Q1b, Q1);
            if(answers[0]!=null)
            {
                //move to the next page
                page1.setVisible(false);
                page2.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
           
        
    }//GEN-LAST:event_Q1nextMouseClicked

    private void Q2nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q2nextMouseClicked
        /**
         * Sends the radio button and button group to the RMI server's function and inserts the return value to a String array 
         */    
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[1]=rmiserv.YNAnswer(Q2a, Q2b, Q2);
            if(answers[1]!=null)
            {
                //code for moving to the next page
                page2.setVisible(false);
                page3.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }      
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        

    }//GEN-LAST:event_Q2nextMouseClicked

    private void Q3nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q3nextMouseClicked
         /**
         * Sends the radio button and button group to the RMI server's function and inserts the return value to a String array 
         */    
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[2]=rmiserv.YNAnswer(Q3a, Q3b, Q3);
            if(answers[2]!=null)
            {
               //code for moving to the next page
                page3.setVisible(false);
                page4.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }         
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        
        
    }//GEN-LAST:event_Q3nextMouseClicked

    private void Q4nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q4nextMouseClicked
        /**
         * Sends the radio button and button group to the RMI server's function and inserts the return value to a String array 
         */ 
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[3]=rmiserv.GamesAnswer(Q4a, Q4b,Q4c,Q4d,Q4e,Q4f,Q4);
            if(answers[3]!=null)
            { 
                //code for moving to the next page
                page4.setVisible(false);
                page5.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }          
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        
    }//GEN-LAST:event_Q4nextMouseClicked

    private void Q5nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q5nextMouseClicked
        /**
         * Sends the radio button and button group to the RMI server's function and inserts the return value to a String array 
         */ 
        
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[4]=rmiserv.HoursAnswer(Q5a, Q5b,Q5c,Q5,1);
            if(answers[4]!=null)
            { 
                //code for moving to the next page
                page5.setVisible(false);
                page6.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }  
                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }

    }//GEN-LAST:event_Q5nextMouseClicked

    private void Q6nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q6nextMouseClicked
        /**
         * Sends the radio button and button group to the RMI server's function and inserts the return value to a String array 
         */ 
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[5]=rmiserv.YNAnswer(Q6a, Q6b, Q6);
            if(answers[5]!=null)
            { 
                //code for moving to the next page
                page6.setVisible(false);
                page7.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }        
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        

    }//GEN-LAST:event_Q6nextMouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        /**
         * Sends the radio button and button group to the RMI server's function and inserts the return value to a String array 
         * And finally submits the array to the server and send the data to the database.
         */ 
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[6]=rmiserv.HoursAnswer(Q7a, Q7b,Q7c,Q7,2);
            if(answers[6]!=null)
            { 
                //code for moving to the next page
                page7.setVisible(false);
                endpoint.setVisible(true);
                String ans = rmiserv.SubmitResults(answers);
                System.out.println("final "+ ans);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            } 

                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
       

    }//GEN-LAST:event_SubmitMouseClicked

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        // exit button
        System.exit(0);
    }//GEN-LAST:event_exitbtnMouseClicked

    private void menubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseClicked
        // Back to main menu
        MainUI nxt = new MainUI();
        setVisible(false);
        nxt.setVisible(true);
    }//GEN-LAST:event_menubtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.ButtonGroup Q1;
    private javax.swing.JRadioButton Q1a;
    private javax.swing.JLabel Q1a1;
    private javax.swing.JLabel Q1a2;
    private javax.swing.JRadioButton Q1b;
    private javax.swing.JLabel Q1next;
    private javax.swing.ButtonGroup Q2;
    private javax.swing.JRadioButton Q2a;
    private javax.swing.JLabel Q2a1;
    private javax.swing.JLabel Q2a10;
    private javax.swing.JLabel Q2a11;
    private javax.swing.JLabel Q2a12;
    private javax.swing.JLabel Q2a13;
    private javax.swing.JLabel Q2a14;
    private javax.swing.JLabel Q2a15;
    private javax.swing.JLabel Q2a16;
    private javax.swing.JLabel Q2a17;
    private javax.swing.JLabel Q2a18;
    private javax.swing.JLabel Q2a2;
    private javax.swing.JLabel Q2a3;
    private javax.swing.JLabel Q2a4;
    private javax.swing.JLabel Q2a5;
    private javax.swing.JLabel Q2a6;
    private javax.swing.JLabel Q2a7;
    private javax.swing.JLabel Q2a8;
    private javax.swing.JLabel Q2a9;
    private javax.swing.JRadioButton Q2b;
    private javax.swing.JLabel Q2next;
    private javax.swing.ButtonGroup Q3;
    private javax.swing.JRadioButton Q3a;
    private javax.swing.JRadioButton Q3b;
    private javax.swing.JLabel Q3next;
    private javax.swing.ButtonGroup Q4;
    private javax.swing.JRadioButton Q4a;
    private javax.swing.JRadioButton Q4b;
    private javax.swing.JRadioButton Q4c;
    private javax.swing.JRadioButton Q4d;
    private javax.swing.JRadioButton Q4e;
    private javax.swing.JRadioButton Q4f;
    private javax.swing.JLabel Q4next;
    private javax.swing.ButtonGroup Q5;
    private javax.swing.JRadioButton Q5a;
    private javax.swing.JRadioButton Q5b;
    private javax.swing.JRadioButton Q5c;
    private javax.swing.JLabel Q5next;
    private javax.swing.ButtonGroup Q6;
    private javax.swing.JRadioButton Q6a;
    private javax.swing.JRadioButton Q6b;
    private javax.swing.JLabel Q6next;
    private javax.swing.ButtonGroup Q7;
    private javax.swing.JRadioButton Q7a;
    private javax.swing.JRadioButton Q7b;
    private javax.swing.JRadioButton Q7c;
    private javax.swing.JLabel Submit;
    private javax.swing.JPanel endpoint;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel menubtn;
    private javax.swing.JPanel page1;
    private javax.swing.JPanel page2;
    private javax.swing.JPanel page3;
    private javax.swing.JPanel page4;
    private javax.swing.JPanel page5;
    private javax.swing.JPanel page6;
    private javax.swing.JPanel page7;
    // End of variables declaration//GEN-END:variables
}
